---
env:
  BUILDKITE_DOCKER_COMPOSE_CONTAINER: build
  BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml
steps:
  - wait

  - name: "Test It"
    command: "npm install && npm test"

  - wait

  - name: ":nodejs: Build It"
    command: "npm run build:prod"
    artifact_paths: "dist/**/*"

  - wait

  - name: ":shipit: Ship It"
    command: "buildkite-agent artifact download 'dist/**/*' ."
    branches: master
