---
env:
  BUILDKITE_DOCKER_COMPOSE_CONTAINER: build
  BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml

steps:
  - wait

  - name: "Test It"
    command: "npm install && npm test"

  - wait

  - name: ":nodejs: Build It"
    command: "npm install && npm run deploy:staging; npm run cleanup"
