---
env:
  BUILDKITE_DOCKER_COMPOSE_CONTAINER: build
  BUILDKITE_DOCKER_COMPOSE_FILE: docker-compose.buildkite.yml

steps:

  - wait

  - name: ":nodejs: Test It"
    command: "npm install && npm test"
    agents:
      queue: native

  - wait

  - name: ":shipit: Ship It"
    command: "npm install && npm run deploy:staging; npm run cleanup"
    branches: master
    agents:
      queue: native
